#!/usr/bin/env python3

import os
import sys


PATH = os.path.join(os.getcwd(), '.versiondir')
def cat_version(filename, version):

    for file in os.listdir(PATH):
        if file == filename + '.' + str(version):
            with open(os.path.join(PATH, file)) as f:
                print(f.read())



def main():
    if len(sys.argv) < 3:
        print("Usage: ./catversion <filename> <version>")
        return
    filename = sys.argv[1]
    version = sys.argv[2]
    cat_version(filename, version)

    

if __name__ == '__main__':
    main()