#!/usr/bin/env python3

import os
import shutil

PATH = os.path.join(os.getcwd(), '.versiondir')

def main():
    os.system('fusermount -u mount')
    shutil.rmtree(PATH)
    

if __name__ == '__main__':
    main()